### ISSUE TITLE
[Bug] Not able to create a school type e-Samwad User

### ISSUE THREAD

**Issue by aakashyadav-kgp** [Samarth-HP/admin-ts#169]
Description: We are trying to create a school type user for UDISE 2040601901 but not able to because there exists a user by that username. As shown in the error below

![Image](https://github.com/Samarth-HP/admin-ts/assets/111346170/e7ecc113-0e6e-4850-a6c6-44d456ce5b70)

But when we search fusion auth no user exists by exact username. 

![Image](https://github.com/Samarth-HP/admin-ts/assets/111346170/9a0678ff-d0e9-4c2d-8fd8-7e367b25a77b)

Acceptance Criteria:

1. We should be able to create user with these credentials.

**Comment by amit-s19** [comment]
Hi, this is likely a fusionauth related issue. I will reindex fusionauth at night to check if the issue is resolved or not. In a case it doesn't resolve we should take help from Abhishek Mishra regarding this.

**Comment by amit-s19** [comment]
@choxx need your help

**Comment by choxx** [comment]
There was a shared memory error thrown by the Postgres container; causing failure to the REINDEX requests. 


![Image](https://github.com/Samarth-HP/admin-ts/assets/11666456/ed27bea3-0770-4044-8a4c-61fbc13efb43)


I increased the shared memory of the container and the issue is gone. @amit-s19 can you verify if the user is appearing in the search results?

**Comment by amit-s19** [comment]
![Image](https://github.com/Samarth-HP/admin-ts/assets/46066481/64625df9-8902-4f02-b443-f44fed6bfaae)

User is now available in search results
