### ISSUE TITLE
[Bug] Not able to create user on Shiksha saathi

### ISSUE THREAD

**Issue by aakashyadav-kgp** [Samarth-HP/admin-ts#170]
Description: Not able to create user with username: una_pri_basoli. Error says user already exists with this username. But searching fusion auth and admin console with that username doesn't show any users. 

![Image](https://user-images.githubusercontent.com/111346170/244283490-78dca8c2-414a-4dbd-88c4-e3e9697ec16c.png)

![Image](https://user-images.githubusercontent.com/111346170/244283551-f6e8b927-aca0-49a5-91c6-c55d8779f423.png)

**Comment by amit-s19** [comment]
Hi, this is likely a fusionauth related issue. I will reindex fusionauth at night to check if the issue is resolved or not. In a case it doesn't resolve we should take help from Abhishek Mishra regarding this.

**Comment by amit-s19** [comment]
@choxx need your help on this one

**Comment by choxx** [comment]
There was a shared memory error thrown by the Postgres container; causing failure to the REINDEX requests. 


![Image](https://github.com/Samarth-HP/admin-ts/assets/11666456/ed27bea3-0770-4044-8a4c-61fbc13efb43)


I increased the shared memory of the container and the issue is gone. @amit-s19 can you verify if the user is appearing in the search results?

**Comment by amit-s19** [comment]
![Image](https://github.com/Samarth-HP/admin-ts/assets/46066481/a458caa5-985c-4f83-b03e-b5b662c55669)

User una_pri_basoli is now available in search results
